name:                 crit
version:              0.1.0.0
visibility:           public
id:                   crit-0.1.0.0-inplace
key:                  crit-0.1.0.0-inplace
synopsis:             Critical values of integer polynomials — the construction
abi:                  inplace
exposed:              True
exposed-modules:
    Bezout Construct Factor Poly QPoly Radicals Roots Verify WebCore

import-dirs:
    "/Users/drakezhard/Projects/Tomorrow's Talk/CriticalValues/haskell/dist-newstyle/build/aarch64-osx/ghc-9.10.3/crit-0.1.0.0/build"

library-dirs:
    "/Users/drakezhard/Projects/Tomorrow's Talk/CriticalValues/haskell/dist-newstyle/build/aarch64-osx/ghc-9.10.3/crit-0.1.0.0/build"
    /opt/homebrew/lib

library-dirs-static:
    "/Users/drakezhard/Projects/Tomorrow's Talk/CriticalValues/haskell/dist-newstyle/build/aarch64-osx/ghc-9.10.3/crit-0.1.0.0/build"
    /opt/homebrew/lib

dynamic-library-dirs:
    "/Users/drakezhard/Projects/Tomorrow's Talk/CriticalValues/haskell/dist-newstyle/build/aarch64-osx/ghc-9.10.3/crit-0.1.0.0/build"
    /opt/homebrew/lib

data-dir:
    "/Users/drakezhard/Projects/Tomorrow's Talk/CriticalValues/haskell/."

hs-libraries:         HScrit-0.1.0.0-inplace
include-dirs:         /opt/homebrew/include
depends:              base-4.20.2.0-754f
haddock-interfaces:
    "/Users/drakezhard/Projects/Tomorrow's Talk/CriticalValues/haskell/dist-newstyle/build/aarch64-osx/ghc-9.10.3/crit-0.1.0.0/doc/html/crit/crit.haddock"

haddock-html:
    "/Users/drakezhard/Projects/Tomorrow's Talk/CriticalValues/haskell/dist-newstyle/build/aarch64-osx/ghc-9.10.3/crit-0.1.0.0/doc/html/crit"
